<?php

namespace AlxDorosenco\VatlayerForLaravel\Tests\Unit\Factory\Types;

use AlxDorosenco\VatlayerForLaravel\Factory\Types\Types;
use AlxDorosenco\VatlayerForLaravel\Tests\TestCase;

class TypesTest extends TestCase
{
    /**
     * @var Types
     */
    private $types;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->types = new Types();
    }

    public function testSetFormatMethod()
    {
        $type = $this->types->setFormat(1);

        $this->assertEquals($this->types, $type);
        $this->assertEquals(1, $this->types->getData()['format']);
    }

    public function testGetDataMethod()
    {
        $data = $this->types->getData();

        $this->assertIsArray($data);
        $this->assertEquals([], $data);
    }

    public function testGetTypeMethod()
    {
        $type = $this->types->getType();

        $this->assertIsString($type);
        $this->assertEquals('types', $type);
    }
}
