<?php

namespace AlxDorosenco\VatlayerForLaravel\Tests\Unit\Http;

use AlxDorosenco\VatlayerForLaravel\Http\Response;
use AlxDorosenco\VatlayerForLaravel\Tests\TestCase;

class ResponseTest extends TestCase
{
    /**
     * @var Response
     */
    private $response;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->response = new Response([], [], []);
    }

    public function testGetHeadersMethod()
    {
        $this->assertIsArray($this->response->getHeaders());
    }

    public function testGetBodyMethod()
    {
        $this->assertIsArray($this->response->getBody());
    }

    public function testGetErrorMethod()
    {
        $this->assertIsArray($this->response->getError());
    }
}
