<?php

namespace AlxDorosenco\VatlayerForLaravel\Tests\Unit\Factory\Rates;

use AlxDorosenco\VatlayerForLaravel\Factory\Rates\RateList;
use Tests\TestCase;

class RateListTest extends TestCase
{
    /**
     * @var RateList
     */
    private $rateList;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->rateList = new RateList();
    }

    public function testGetDataMethod()
    {
        $data = $this->rateList->getData();

        $this->assertIsArray($data);
        $this->assertEquals([], $data);
    }

    public function testGetTypeMethod()
    {
        $type = $this->rateList->getType();

        $this->assertIsString($type);
        $this->assertEquals('rate_list', $type);
    }
}
